version: '3.8'

services:
  merchant-api:
    build:
      dockerfile: ./dockers/merchant-api/Dockerfile
    container_name: merchant-api
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    volumes:
      - ./packages/merchant-api:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: