# version: '3.8'

# services:
#   merchant-api:
#     build:
#       dockerfile: ./dockers/merchant-api/Dockerfile
#     container_name: merchant-api
#     ports:
#       - "8080:80"
#     depends_on:
#       - mongodb
#     volumes:
#       - ./packages/merchant-api:/app

#   mongodb:
#      image: mongo:latest
#      ports:
#        - "27017:27017"
#      volumes:
#        - mongodb_data:/data/db
  
  
# volumes:
#   mongodb_data:

version: "3.4"

services:
  
  merchant-api:
    build:
      dockerfile: ./dockers/merchant-api/Dockerfile
    container_name: merchant-api
    ports:
      - "8080:80"
    depends_on:
      - postgresql
    volumes:
      - ./packages/merchant-api:/app

  postgresql:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastapi-db
    ports:
      - "5432:5432"
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data

  postgresql-test:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db-test
    ports:
      - "5431:5432"
    # volumes:
    #   - ./postgresql-test:/var/lib/postgresql/data

  redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
#     volumes:
#       - redis:/data

  rabbitmq:
    image: rabbitmq:3.9.7
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=password

# volumes:
#   redis: